version: "3.9"

services:
  mysql:
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: "root_password"
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
        - "${DB_PORT}:3306"
    networks: [ "golangpractice" ]
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/init.sql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80    
    networks: [ "golangpractice" ]

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 -js -server_name nats-1 -routes nats://nats-1:6222,nats://nats-2:6222,nats://nats-3:6222"
    networks: [ "golangpractice" ]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js -server_name nats-2"
    networks: ["golangpractice"]
    depends_on: ["nats"]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222 -js -server_name nats-3"
    networks: ["golangpractice"]
    depends_on: ["nats"]


networks:
  golangpractice:
    name: golangpractice
    driver: bridge
