version: "3.9"

services:
  golang_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: "9000"
    networks:
      - golangpractice
    ports:
      - "9000:9000"

networks:
  golangpractice:
    driver: bridge