version: "3.9"

services:
  golang_server:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_PORT: "9000"
    networks:
      - golangpractice
    ports:
      - "9000:9000"

  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222 "
    networks: [ "golangpractice" ]
  nats-1:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "golangpractice" ]
    depends_on: [ "nats" ]
  nats-2:
    image: nats
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: [ "golangpractice" ]
    depends_on: [ "nats" ]

networks:
  golangpractice:
    name: golangpractice
    driver: bridge
