version: "3.9"

services:
  gomysql:
    container_name: gomysql
    image: mysql:8.0.31
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
        - "${DB_PORT}:3306"
    networks: 
      - go_network
    volumes:
      - ./migration.sql:/docker-entrypoint-initdb.d/init.sql

  gophpmyadmin:
    container_name: gophpmyadmin
    image: phpmyadmin
    depends_on:
      - gomysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_password
      UPLOAD_LIMIT: 300M
    restart: always
    ports:
      - 8081:80    
    networks:
     - go_network

  gonats1:
    container_name: gonats1
    image: nats
    entrypoint: /nats-server
    command: >
      --server_name N1
      --cluster_name golang_cluster
      --js
      --sd /data
      --cluster nats://0.0.0.0:6222
      --routes nats://gonats2:6222,nats://gonats3:6222
    networks:
      - go_network
    ports:
      - 4222:4222
      - 8222:8222

  gonats2:
    container_name: gonats2
    image: nats
    entrypoint: /nats-server
    command: > 
      --server_name N2 
      --cluster_name golang_cluster 
      --js 
      --sd /data 
      --cluster nats://0.0.0.0:6222 
      --routes nats://gonats1:6222,nats://gonats3:6222 
    networks:
      - go_network

  gonats3:
    container_name: gonats3
    image: nats
    entrypoint: /nats-server
    command: >
      --server_name N3 
      --cluster_name golang_cluster 
      --js 
      --sd /data 
      --cluster nats://0.0.0.0:6222 
      --routes nats://gonats1:6222,nats://gonats2:6222 
    networks:
      - go_network

networks:
  go_network:
    name: go_network
    driver: bridge
